package main

import (
	"os"

	"github.com/spf13/viper"
)

type Config struct {
	Host     string `mapstructure:"host"`
	Password string
	Port     int `mapstructure:"port"`
	Database int
	File     string `mapstructure:"file"`
}

var _config Config

func InitConfig(configFile string) (err error) {
	viper.SetDefault("host", "127.0.0.1")
	viper.SetDefault("port", 6379)
	viper.SetDefault("database", 0)
	viper.SetDefault("file", "./redis.cmd")

	viper.SetConfigFile(configFile)
	err = viper.ReadInConfig()
	if err != nil {
		return err
	}
	if err = viper.Unmarshal(&_config); err != nil {
		return err
	}
	return nil
}

func IsExist(path string) bool {
	_, err := os.Stat(path) //os.Stat获取文件信息
	if err != nil {
		return os.IsExist(err)
	}
	return true
}

var cmdTypeMap = map[string]string{
	"command":                    "commandsinfo",
	"clientgetname":              "string",
	"echo":                       "string",
	"ping":                       "status",
	"quit":                       "status",
	"del":                        "int",
	"unlink":                     "int",
	"dump":                       "string",
	"exists":                     "int",
	"expire":                     "bool",
	"expireat":                   "bool",
	"keys":                       "stringslice",
	"migrate":                    "status",
	"move":                       "bool",
	"objectrefcount":             "int",
	"objectencoding":             "string",
	"objectidletime":             "duration",
	"persist":                    "bool",
	"pexpire":                    "bool",
	"pexpireat":                  "bool",
	"pttl":                       "duration",
	"randomkey":                  "string",
	"rename":                     "status",
	"renamenx":                   "bool",
	"restore":                    "status",
	"restorereplace":             "status",
	"sort":                       "stringslice",
	"sortstore":                  "int",
	"sortinterfaces":             "slice",
	"touch":                      "int",
	"ttl":                        "duration",
	"type":                       "status",
	"scan":                       "scan",
	"sscan":                      "scan",
	"hscan":                      "scan",
	"zscan":                      "scan",
	"append":                     "int",
	"bitcount":                   "int",
	"bitopand":                   "int",
	"bitopor":                    "int",
	"bitopxor":                   "int",
	"bitopnot":                   "int",
	"bitpos":                     "int",
	"decr":                       "int",
	"decrby":                     "int",
	"get":                        "string",
	"getbit":                     "int",
	"getrange":                   "string",
	"getset":                     "string",
	"incr":                       "int",
	"incrby":                     "int",
	"incrbyfloat":                "float",
	"mget":                       "slice",
	"mset":                       "status",
	"msetnx":                     "bool",
	"set":                        "status",
	"setbit":                     "int",
	"setnx":                      "bool",
	"setxx":                      "bool",
	"setrange":                   "int",
	"strlen":                     "int",
	"hdel":                       "int",
	"hexists":                    "bool",
	"hget":                       "string",
	"hgetall":                    "stringstringmap",
	"hincrby":                    "int",
	"hincrbyfloat":               "float",
	"hkeys":                      "stringslice",
	"hlen":                       "int",
	"hmget":                      "slice",
	"hmset":                      "status",
	"hset":                       "bool",
	"hsetnx":                     "bool",
	"hvals":                      "stringslice",
	"blpop":                      "stringslice",
	"brpop":                      "stringslice",
	"brpoplpush":                 "string",
	"lindex":                     "string",
	"linsert":                    "int",
	"linsertbefore":              "int",
	"linsertafter":               "int",
	"llen":                       "int",
	"lpop":                       "string",
	"lpush":                      "int",
	"lpushx":                     "int",
	"lrange":                     "stringslice",
	"lrem":                       "int",
	"lset":                       "status",
	"ltrim":                      "status",
	"rpop":                       "string",
	"rpoplpush":                  "string",
	"rpush":                      "int",
	"rpushx":                     "int",
	"sadd":                       "int",
	"scard":                      "int",
	"sdiff":                      "stringslice",
	"sdiffstore":                 "int",
	"sinter":                     "stringslice",
	"sinterstore":                "int",
	"sismember":                  "bool",
	"smembers":                   "stringslice",
	"smembersmap":                "stringstructmap",
	"smove":                      "bool",
	"spop":                       "string",
	"spopn":                      "stringslice",
	"srandmember":                "string",
	"srandmembern":               "stringslice",
	"srem":                       "int",
	"sunion":                     "stringslice",
	"sunionstore":                "int",
	"xadd":                       "string",
	"xdel":                       "int",
	"xlen":                       "int",
	"xrange":                     "xmessageslice",
	"xrangen":                    "xmessageslice",
	"xrevrange":                  "xmessageslice",
	"xrevrangen":                 "xmessageslice",
	"xread":                      "xstreamslice",
	"xreadstreams":               "xstreamslice",
	"xgroupcreate":               "status",
	"xgroupcreatemkstream":       "status",
	"xgroupsetid":                "status",
	"xgroupdestroy":              "int",
	"xgroupdelconsumer":          "int",
	"xreadgroup":                 "xstreamslice",
	"xack":                       "int",
	"xpending":                   "xpending",
	"xpendingext":                "xpendingext",
	"xclaim":                     "xmessageslice",
	"xclaimjustid":               "stringslice",
	"xtrim":                      "int",
	"xtrimapprox":                "int",
	"bzpopmax":                   "zwithkey",
	"bzpopmin":                   "zwithkey",
	"zadd":                       "int",
	"zaddnx":                     "int",
	"zaddxx":                     "int",
	"zaddch":                     "int",
	"zaddnxch":                   "int",
	"zaddxxch":                   "int",
	"zincr":                      "float",
	"zincrnx":                    "float",
	"zincrxx":                    "float",
	"zcard":                      "int",
	"zcount":                     "int",
	"zlexcount":                  "int",
	"zincrby":                    "float",
	"zinterstore":                "int",
	"zpopmax":                    "zslice",
	"zpopmin":                    "zslice",
	"zrange":                     "stringslice",
	"zrangewithscores":           "zslice",
	"zrangebyscore":              "stringslice",
	"zrangebylex":                "stringslice",
	"zrangebyscorewithscores":    "zslice",
	"zrank":                      "int",
	"zrem":                       "int",
	"zremrangebyrank":            "int",
	"zremrangebyscore":           "int",
	"zremrangebylex":             "int",
	"zrevrange":                  "stringslice",
	"zrevrangewithscores":        "zslice",
	"zrevrangebyscore":           "stringslice",
	"zrevrangebylex":             "stringslice",
	"zrevrangebyscorewithscores": "zslice",
	"zrevrank":                   "int",
	"zscore":                     "float",
	"zunionstore":                "int",
	"pfadd":                      "int",
	"pfcount":                    "int",
	"pfmerge":                    "status",
	"bgrewriteaof":               "status",
	"bgsave":                     "status",
	"clientkill":                 "status",
	"clientkillbyfilter":         "int",
	"clientlist":                 "string",
	"clientpause":                "bool",
	"clientid":                   "int",
	"configget":                  "slice",
	"configresetstat":            "status",
	"configset":                  "status",
	"configrewrite":              "status",
	"dbsize":                     "int",
	"flushall":                   "status",
	"flushallasync":              "status",
	"flushdb":                    "status",
	"flushdbasync":               "status",
	"info":                       "string",
	"lastsave":                   "int",
	"save":                       "status",
	"shutdown":                   "status",
	"shutdownsave":               "status",
	"shutdownnosave":             "status",
	"slaveof":                    "status",
	"time":                       "time",
	"eval":                       "cmd",
	"evalsha":                    "cmd",
	"scriptexists":               "boolslice",
	"scriptflush":                "status",
	"scriptkill":                 "status",
	"scriptload":                 "string",
	"debugobject":                "string",
	"publish":                    "int",
	"pubsubchannels":             "stringslice",
	"pubsubnumsub":               "stringintmap",
	"pubsubnumpat":               "int",
	"clusterslots":               "clusterslots",
	"clusternodes":               "string",
	"clustermeet":                "status",
	"clusterforget":              "status",
	"clusterreplicate":           "status",
	"clusterresetsoft":           "status",
	"clusterresethard":           "status",
	"clusterinfo":                "string",
	"clusterkeyslot":             "int",
	"clustergetkeysinslot":       "stringslice",
	"clustercountfailurereports": "int",
	"clustercountkeysinslot":     "int",
	"clusterdelslots":            "status",
	"clusterdelslotsrange":       "status",
	"clustersaveconfig":          "status",
	"clusterslaves":              "stringslice",
	"clusterfailover":            "status",
	"clusteraddslots":            "status",
	"clusteraddslotsrange":       "status",
	"geoadd":                     "int",
	"geopos":                     "geopos",
	"georadius":                  "geolocation",
	"georadiusro":                "geolocation",
	"georadiusbymember":          "geolocation",
	"georadiusbymemberro":        "geolocation",
	"geodist":                    "float",
	"geohash":                    "stringslice",
	"readonly":                   "status",
	"readwrite":                  "status",
}
